server:
   port: 9010
   
spring:
   application:
      name: GRAVEYARD-SERVICE
   cloud:
      config:
         import-check:
            enabled: false
   zipkin:
      base-url: http://localhost:9411/
