server:
   port: 9003
   
spring:
   application:
      name: PRODUCT-SERVICE
   cloud:
      config:
         import-check:
            enabled: false
   zipkin:
      base-url: http://localhost:9411/
